### ISSUE TITLE
Usage of AppContext.get()

### ISSUE THREAD

**Issue by yadavvi91** [vRallev/job-sample#1]
~~What is the usage of `AppContext.get()` in the `ReminderEngine` and `SyncEngine`, wouldn't passing the **Application context** also have worked?~~

~~Say, we could create the `ReminderEngine` and `SyncEngine` (as a singleton) in the Application class itself and then access it via the same `ReminderEngine.instance()`, would that have been wrong?~~

Just read the [android-job demo app](https://github.com/evernote/android-job/tree/master/demo) and I see that, that is how it is done.

**Comment by vRallev** [comment]
Glad you found it. `AppContext` is just one of my other helper libs: https://github.com/vRallev/app-context
